"""
Report generator using RAG (Retrieval-Augmented Generation).
"""
from typing import Optional, Dict, List
from .retriever import retrieve_knowledge
from .llm import generate_text


def generate_report(
    confidence_score: float,
    num_detections: int = 0,
    boxes: Optional[List] = None,
    patient_info: Optional[Dict] = None
) -> str:
    """
    Generate a clinical report using RAG.
    
    Args:
        confidence_score: Detection confidence score (0-1)
        num_detections: Number of detected nodules
        boxes: List of bounding boxes (optional)
        patient_info: Patient information dictionary (optional)
    
    Returns:
        Generated clinical report text
    """
    # Retrieve relevant knowledge
    query = f"lung nodule detection confidence {confidence_score:.2f} detections {num_detections}"
    knowledge = retrieve_knowledge(query, confidence_score, num_detections, top_k=3)
    
    # Build context from retrieved knowledge
    context = "\n".join([item["content"] for item in knowledge])
    
    # Build prompt for LLM
    prompt = f"""You are a clinical AI assistant generating a medical report for lung nodule detection.

Context:
{context}

Detection Results:
- Confidence Score: {confidence_score:.3f} ({confidence_score*100:.1f}%)
- Number of Detections: {num_detections}

Patient Information:
{patient_info if patient_info else "Not provided"}

Generate a concise, professional clinical report summarizing the AI detection results. 
Include:
1. Summary of findings
2. Confidence assessment
3. Recommendations for clinical follow-up
4. Important disclaimers about AI-assisted diagnosis

Keep the report clear, professional, and suitable for clinical use.
"""
    
    # Generate report using LLM
    report = generate_text(prompt)
    
    if report is None:
        # Fallback to template-based report
        return _generate_template_report(confidence_score, num_detections, boxes)
    
    return report


def _generate_template_report(
    confidence_score: float,
    num_detections: int,
    boxes: Optional[List] = None
) -> str:
    """Generate a template-based report as fallback."""
    report_lines = []
    report_lines.append("AI-Powered Lung Nodule Detection Report")
    report_lines.append("=" * 50)
    report_lines.append("")
    
    report_lines.append("SUMMARY OF FINDINGS:")
    report_lines.append(f"- Overall Detection Confidence: {confidence_score:.3f} ({confidence_score*100:.1f}%)")
    report_lines.append(f"- Number of Detected Lesions: {num_detections}")
    
    if boxes:
        report_lines.append(f"- Bounding Boxes: {len(boxes)} detected regions")
    
    report_lines.append("")
    report_lines.append("CLINICAL ASSESSMENT:")
    
    if confidence_score >= 0.8:
        assessment = "High confidence detection. Clinical correlation and follow-up imaging recommended."
    elif confidence_score >= 0.5:
        assessment = "Moderate confidence detection. Further evaluation may be warranted."
    else:
        assessment = "Low confidence detection. Results should be interpreted with caution."
    
    report_lines.append(assessment)
    
    report_lines.append("")
    report_lines.append("RECOMMENDATIONS:")
    report_lines.append("- Review by a qualified radiologist is required")
    report_lines.append("- Consider follow-up imaging based on clinical context")
    report_lines.append("- Patient risk factors should be considered")
    
    report_lines.append("")
    report_lines.append("DISCLAIMER:")
    report_lines.append("This report is generated by an AI system and is intended for clinical decision support only.")
    report_lines.append("It should not replace professional medical judgment or clinical evaluation.")
    
    return "\n".join(report_lines)
